/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabajopractico_4;


import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santi
 */
public class Colegio extends javax.swing.JFrame {

    
    LinkedList<Alumno> listAlum = new LinkedList<Alumno>();
    LinkedList<Materia> listMate = new LinkedList<Materia>();
    /**
     * Creates new form main
     */
    public Colegio() {
        initComponents();
        
        
        String[] nombreColum ={"Id Materia","Nombre","Año"};
        DefaultTableModel model = new DefaultTableModel(nombreColum, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        };
        tblListaMaterias.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlColegio = new javax.swing.JPanel();
        pnlTituloMate1 = new javax.swing.JPanel();
        txtTituloMate1 = new javax.swing.JLabel();
        pnlContenidoMate1 = new javax.swing.JPanel();
        cbxAlumnos = new javax.swing.JComboBox<>();
        txtAlumCombo = new javax.swing.JLabel();
        txtNombreCole = new javax.swing.JLabel();
        txtApellidoCole = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaMaterias = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlFormulario = new javax.swing.JPanel();
        pnlTituloForm = new javax.swing.JPanel();
        txtTituloForm = new javax.swing.JLabel();
        pnlContenidoMate4 = new javax.swing.JPanel();
        cbxMateriaForm = new javax.swing.JComboBox<>();
        txtAlumCombo3 = new javax.swing.JLabel();
        txtNombreCole3 = new javax.swing.JLabel();
        txtApellidoCole3 = new javax.swing.JLabel();
        btnInscribir = new javax.swing.JButton();
        txtMateriaCombo = new javax.swing.JLabel();
        cbxAlumnosForm = new javax.swing.JComboBox<>();
        pnlMateria = new javax.swing.JPanel();
        pnlContenidoMate = new javax.swing.JPanel();
        txtIdMateria = new javax.swing.JLabel();
        txtNombreMate = new javax.swing.JLabel();
        txtAnio = new javax.swing.JLabel();
        txfIdMate = new javax.swing.JTextField();
        txfNombreMate = new javax.swing.JTextField();
        txfAnio = new javax.swing.JTextField();
        btnBorrarMate = new javax.swing.JButton();
        btnGuardarMate = new javax.swing.JButton();
        pnlTituloMate = new javax.swing.JPanel();
        txtTituloMate = new javax.swing.JLabel();
        pnlAlumno = new javax.swing.JPanel();
        pnlConetnidoAlum = new javax.swing.JPanel();
        txtLegajo = new javax.swing.JLabel();
        txtNombreAlum = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txfLegajo = new javax.swing.JTextField();
        txfNombreAlum = new javax.swing.JTextField();
        txfApellido = new javax.swing.JTextField();
        btnBorrarAlum = new javax.swing.JButton();
        btnGuardarAlum = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        pnlColegio.setBackground(new java.awt.Color(163, 223, 236));

        pnlTituloMate1.setBackground(new java.awt.Color(255, 153, 153));
        pnlTituloMate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTituloMate1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTituloMate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/colegio.png"))); // NOI18N
        txtTituloMate1.setText("Colegio");

        javax.swing.GroupLayout pnlTituloMate1Layout = new javax.swing.GroupLayout(pnlTituloMate1);
        pnlTituloMate1.setLayout(pnlTituloMate1Layout);
        pnlTituloMate1Layout.setHorizontalGroup(
            pnlTituloMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloMate1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloMate1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloMate1Layout.setVerticalGroup(
            pnlTituloMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloMate1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloMate1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContenidoMate1.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoMate1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbxAlumnos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlumnosActionPerformed(evt);
            }
        });

        txtAlumCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAlumCombo.setText("Alumno");

        txtNombreCole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreCole.setText(" ");

        txtApellidoCole.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoCole.setText(" ");

        tblListaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id Materia", "Nombre", "Año"
            }
        ));
        jScrollPane1.setViewportView(tblListaMaterias);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Materias:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText(" ");

        javax.swing.GroupLayout pnlContenidoMate1Layout = new javax.swing.GroupLayout(pnlContenidoMate1);
        pnlContenidoMate1.setLayout(pnlContenidoMate1Layout);
        pnlContenidoMate1Layout.setHorizontalGroup(
            pnlContenidoMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoMate1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenidoMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoMate1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(pnlContenidoMate1Layout.createSequentialGroup()
                        .addComponent(txtAlumCombo)
                        .addGroup(pnlContenidoMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlContenidoMate1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(txtNombreCole)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtApellidoCole)
                                .addGap(107, 107, 107))
                            .addGroup(pnlContenidoMate1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        pnlContenidoMate1Layout.setVerticalGroup(
            pnlContenidoMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoMate1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlContenidoMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlumCombo)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlContenidoMate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCole)
                    .addComponent(txtApellidoCole))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlColegioLayout = new javax.swing.GroupLayout(pnlColegio);
        pnlColegio.setLayout(pnlColegioLayout);
        pnlColegioLayout.setHorizontalGroup(
            pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlContenidoMate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloMate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        pnlColegioLayout.setVerticalGroup(
            pnlColegioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlColegioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloMate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenidoMate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Colegio", pnlColegio);

        pnlFormulario.setBackground(new java.awt.Color(163, 223, 236));

        pnlTituloForm.setBackground(new java.awt.Color(255, 153, 153));
        pnlTituloForm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTituloForm.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTituloForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/formulario-de-contacto.png"))); // NOI18N
        txtTituloForm.setText("Formulario de Inscripción");

        javax.swing.GroupLayout pnlTituloFormLayout = new javax.swing.GroupLayout(pnlTituloForm);
        pnlTituloForm.setLayout(pnlTituloFormLayout);
        pnlTituloFormLayout.setHorizontalGroup(
            pnlTituloFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloFormLayout.setVerticalGroup(
            pnlTituloFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlContenidoMate4.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoMate4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbxMateriaForm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxMateriaForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMateriaFormActionPerformed(evt);
            }
        });

        txtAlumCombo3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAlumCombo3.setText("Alumno");

        txtNombreCole3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreCole3.setText(" ");

        txtApellidoCole3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidoCole3.setText(" ");

        btnInscribir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInscribir.setText("Inscribir");
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        txtMateriaCombo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMateriaCombo.setText("Materia");

        cbxAlumnosForm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxAlumnosForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAlumnosFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenidoMate4Layout = new javax.swing.GroupLayout(pnlContenidoMate4);
        pnlContenidoMate4.setLayout(pnlContenidoMate4Layout);
        pnlContenidoMate4Layout.setHorizontalGroup(
            pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoMate4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAlumCombo3)
                    .addComponent(txtMateriaCombo))
                .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoMate4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtNombreCole3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellidoCole3)
                        .addGap(107, 107, 107))
                    .addGroup(pnlContenidoMate4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxMateriaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxAlumnosForm, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnInscribir)
                        .addContainerGap(61, Short.MAX_VALUE))))
        );
        pnlContenidoMate4Layout.setVerticalGroup(
            pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoMate4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCole3)
                    .addComponent(txtApellidoCole3))
                .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlContenidoMate4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlumCombo3)
                            .addComponent(cbxAlumnosForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlContenidoMate4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMateriaCombo)
                            .addComponent(cbxMateriaForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlContenidoMate4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnInscribir)))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFormularioLayout = new javax.swing.GroupLayout(pnlFormulario);
        pnlFormulario.setLayout(pnlFormularioLayout);
        pnlFormularioLayout.setHorizontalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormularioLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlContenidoMate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTituloForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(125, 125, 125))
        );
        pnlFormularioLayout.setVerticalGroup(
            pnlFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenidoMate4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Formulario de Inscipción", pnlFormulario);

        pnlMateria.setBackground(new java.awt.Color(163, 223, 236));

        pnlContenidoMate.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenidoMate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdMateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdMateria.setText("Id Materia:");

        txtNombreMate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreMate.setText("Nombre:");

        txtAnio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAnio.setText("Año:");

        txfAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfAnioActionPerformed(evt);
            }
        });

        btnBorrarMate.setText("Nuevo");
        btnBorrarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarMateActionPerformed(evt);
            }
        });

        btnGuardarMate.setText("Guardar");
        btnGuardarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlContenidoMateLayout = new javax.swing.GroupLayout(pnlContenidoMate);
        pnlContenidoMate.setLayout(pnlContenidoMateLayout);
        pnlContenidoMateLayout.setHorizontalGroup(
            pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoMateLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdMateria)
                    .addComponent(txtNombreMate)
                    .addComponent(txtAnio))
                .addGap(18, 18, 18)
                .addGroup(pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfIdMate, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txfNombreMate)
                    .addComponent(txfAnio))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContenidoMateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarMate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarMate)
                .addGap(7, 7, 7))
        );
        pnlContenidoMateLayout.setVerticalGroup(
            pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContenidoMateLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMateria)
                    .addComponent(txfIdMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreMate)
                    .addComponent(txfNombreMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnio)
                    .addComponent(txfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(pnlContenidoMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarMate)
                    .addComponent(btnGuardarMate))
                .addContainerGap())
        );

        pnlTituloMate.setBackground(new java.awt.Color(255, 153, 153));
        pnlTituloMate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTituloMate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTituloMate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        txtTituloMate.setText(" Materia");

        javax.swing.GroupLayout pnlTituloMateLayout = new javax.swing.GroupLayout(pnlTituloMate);
        pnlTituloMate.setLayout(pnlTituloMateLayout);
        pnlTituloMateLayout.setHorizontalGroup(
            pnlTituloMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloMateLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(txtTituloMate)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        pnlTituloMateLayout.setVerticalGroup(
            pnlTituloMateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloMateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTituloMate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMateriaLayout = new javax.swing.GroupLayout(pnlMateria);
        pnlMateria.setLayout(pnlMateriaLayout);
        pnlMateriaLayout.setHorizontalGroup(
            pnlMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMateriaLayout.createSequentialGroup()
                .addGroup(pnlMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMateriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlContenidoMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMateriaLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(pnlTituloMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
        );
        pnlMateriaLayout.setVerticalGroup(
            pnlMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMateriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTituloMate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContenidoMate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar Materia", pnlMateria);

        pnlAlumno.setBackground(new java.awt.Color(163, 223, 236));

        pnlConetnidoAlum.setBackground(new java.awt.Color(255, 255, 255));
        pnlConetnidoAlum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtLegajo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLegajo.setText("Legajo:");

        txtNombreAlum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombreAlum.setText("Nombre:");

        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellido.setText("Apellido:");

        txfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfApellidoActionPerformed(evt);
            }
        });

        btnBorrarAlum.setText("Nuevo");
        btnBorrarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAlumActionPerformed(evt);
            }
        });

        btnGuardarAlum.setText("Guardar");
        btnGuardarAlum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConetnidoAlumLayout = new javax.swing.GroupLayout(pnlConetnidoAlum);
        pnlConetnidoAlum.setLayout(pnlConetnidoAlumLayout);
        pnlConetnidoAlumLayout.setHorizontalGroup(
            pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConetnidoAlumLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLegajo)
                    .addComponent(txtNombreAlum)
                    .addComponent(txtApellido))
                .addGap(18, 18, 18)
                .addGroup(pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txfLegajo, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txfNombreAlum)
                    .addComponent(txfApellido))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConetnidoAlumLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBorrarAlum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarAlum)
                .addGap(7, 7, 7))
        );
        pnlConetnidoAlumLayout.setVerticalGroup(
            pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConetnidoAlumLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLegajo)
                    .addComponent(txfLegajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreAlum)
                    .addComponent(txfNombreAlum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido)
                    .addComponent(txfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(pnlConetnidoAlumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrarAlum)
                    .addComponent(btnGuardarAlum))
                .addContainerGap())
        );

        pnlTitulo.setBackground(new java.awt.Color(255, 153, 153));
        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alumno.png"))); // NOI18N
        txtTitulo.setText("Alumno");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAlumnoLayout = new javax.swing.GroupLayout(pnlAlumno);
        pnlAlumno.setLayout(pnlAlumnoLayout);
        pnlAlumnoLayout.setHorizontalGroup(
            pnlAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlumnoLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(pnlAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlConetnidoAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        pnlAlumnoLayout.setVerticalGroup(
            pnlAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlConetnidoAlum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Registrar Alumno", pnlAlumno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfAnioActionPerformed

    private void txfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfApellidoActionPerformed

    private void cbxAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlumnosActionPerformed
        // TODO add your handling code here
        
        Alumno alumno = listAlum.get(cbxAlumnos.getSelectedIndex());
        txtNombreCole.setText(alumno.getNombre());
        txtApellidoCole.setText(alumno.getApellido());
        jLabel2.setText(""+alumno.cantidadMateria());
        
        String[] nombreColum ={"Id Materia","Nombre","Año"};
        DefaultTableModel model = new DefaultTableModel(nombreColum, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        };
        tblListaMaterias.setModel(model);
        
        model.setRowCount(0);
        
        for(Materia m:alumno.getListaDeMate()){
            Object[] mate = {
                m.getIdMateria(),
                m.getNombre(),
                m.getAnio()
            };
            model.addRow(mate);
        }
        
    }//GEN-LAST:event_cbxAlumnosActionPerformed

    private void cbxMateriaFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMateriaFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMateriaFormActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        // TODO add your handling code here:
        
        if(listAlum.get(cbxAlumnosForm.getSelectedIndex()).agregarMateria(listMate.get(cbxMateriaForm.getSelectedIndex()))){
            JOptionPane.showMessageDialog(this, "Inscripcion exitosa");
        }else{
            JOptionPane.showMessageDialog(this, "No se permite inscribir a un alumno en la misma materia");
        }
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void cbxAlumnosFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAlumnosFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAlumnosFormActionPerformed

    private void btnGuardarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumActionPerformed
        // TODO add your handling code here:
        boolean lega=true; 
        
        try {
            if(txfNombreAlum.getText().equals("") || txfLegajo.getText().equals("") || txfApellido.getText().equals("")){

                JOptionPane.showMessageDialog(this, "No puede dejar los campos vacios");
            }else{
                for(Alumno a:listAlum){
                    if(a.getLegajo() == Integer.parseInt(txfLegajo.getText())){
                        lega=false;
                        JOptionPane.showMessageDialog(this, "Error no se permiten legajos duplicados");
                        break;
                    }
                }
                listAlum.add(new Alumno(Integer.parseInt(txfLegajo.getText()), txfApellido.getText(), txfNombreAlum.getText()));
                cbxAlumnosForm.addItem(txfApellido.getText() + " " + txfNombreAlum.getText());
                cbxAlumnos.addItem(txfLegajo.getText());
                txfLegajo.setText("");
                txfNombreAlum.setText("");
                txfApellido.setText("");
                JOptionPane.showMessageDialog(this, "Alumno registrado correctamente");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            txfLegajo.setText("");
            txfNombreAlum.setText("");
            txfApellido.setText("");
        }
        
    }//GEN-LAST:event_btnGuardarAlumActionPerformed

    private void btnBorrarAlumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAlumActionPerformed
        // TODO add your handling code here:
        txfLegajo.setText("");
        txfNombreAlum.setText("");
        txfApellido.setText("");
    }//GEN-LAST:event_btnBorrarAlumActionPerformed

    private void btnBorrarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarMateActionPerformed
        // TODO add your handling code here:
        txfIdMate.setText("");
        txfNombreMate.setText("");
        txfAnio.setText("");
    }//GEN-LAST:event_btnBorrarMateActionPerformed

    private void btnGuardarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMateActionPerformed
        // TODO add your handling code here:
        
        try{
            if(txfIdMate.getText().equals("") || txfNombreMate.getText().equals("") || txfAnio.getText().equals("")){

                JOptionPane.showMessageDialog(this, "No puede dejar los campos vacios");
            }else{
                listMate.add(new Materia(Integer.parseInt(txfIdMate.getText()), txfNombreMate.getText(), Integer.parseInt(txfAnio.getText())));
                cbxMateriaForm.addItem(txfNombreMate.getText() +" - "+ txfAnio.getText());

                txfIdMate.setText("");
                txfNombreMate.setText("");
                txfAnio.setText("");

                JOptionPane.showMessageDialog(this, "Materia registrada correctamente");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            txfIdMate.setText("");
            txfNombreMate.setText("");
            txfAnio.setText("");
        }
    }//GEN-LAST:event_btnGuardarMateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarAlum;
    private javax.swing.JButton btnBorrarMate;
    private javax.swing.JButton btnGuardarAlum;
    private javax.swing.JButton btnGuardarMate;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JComboBox<String> cbxAlumnos;
    private javax.swing.JComboBox<String> cbxAlumnosForm;
    private javax.swing.JComboBox<String> cbxMateriaForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlAlumno;
    private javax.swing.JPanel pnlColegio;
    private javax.swing.JPanel pnlConetnidoAlum;
    private javax.swing.JPanel pnlContenidoMate;
    private javax.swing.JPanel pnlContenidoMate1;
    private javax.swing.JPanel pnlContenidoMate4;
    private javax.swing.JPanel pnlFormulario;
    private javax.swing.JPanel pnlMateria;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JPanel pnlTituloForm;
    private javax.swing.JPanel pnlTituloMate;
    private javax.swing.JPanel pnlTituloMate1;
    private javax.swing.JTable tblListaMaterias;
    private javax.swing.JTextField txfAnio;
    private javax.swing.JTextField txfApellido;
    private javax.swing.JTextField txfIdMate;
    private javax.swing.JTextField txfLegajo;
    private javax.swing.JTextField txfNombreAlum;
    private javax.swing.JTextField txfNombreMate;
    private javax.swing.JLabel txtAlumCombo;
    private javax.swing.JLabel txtAlumCombo3;
    private javax.swing.JLabel txtAnio;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtApellidoCole;
    private javax.swing.JLabel txtApellidoCole3;
    private javax.swing.JLabel txtIdMateria;
    private javax.swing.JLabel txtLegajo;
    private javax.swing.JLabel txtMateriaCombo;
    private javax.swing.JLabel txtNombreAlum;
    private javax.swing.JLabel txtNombreCole;
    private javax.swing.JLabel txtNombreCole3;
    private javax.swing.JLabel txtNombreMate;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtTituloForm;
    private javax.swing.JLabel txtTituloMate;
    private javax.swing.JLabel txtTituloMate1;
    // End of variables declaration//GEN-END:variables
}
